model:
  latent_processor:
    skip_predictor: false
  predictor:
    name: networks.SoftIdentityPredictor
    dim: ${globals.SLOT_DIM}
    sinkhorn_iters: 5
    sinkhorn_tau: 0.1
    cosine_weight: 1.0
    use_flow_iou: false
    flow_iou_weight: 0.0
    use_centroid_dist: false
    straight_through: true
  loss_weights:
    loss_featrec: 1.0
    loss_ss: 0.5
